export class HoSoKhacViewModel {
    public constructor(
        public Id: number = null,
        public KeyId: number = null,
        public DisplayName: string = null
        ){}
}
export class LoaiHoSoDieuTriNoiTru {
    public constructor(
        public PhieuSangLocDinhDuong: number = 1,
        public PhieuKhaiThacTienSuDiUng: number = 2,
        public TrichBienBanHoiChan: number = 3,
        public PhieuTheoDoiChucNangSong: number = 4,
        public PhieuSoKet15NgayDieuTri: number = 5,
        public PhieuTomTatThongTinDieuTri: number = 6,
        public BienBanHoiChanPhauThuat: number = 7,
        public BienBanCamKetGayMeGayTe: number = 9,
        public BienBanCamKetPhauThuat: number = 8,
        public BangKiemAnToanPhauThuat: number = 10,
        public BangKiemAnToanNguoiBenhPhauThuat: number = 11,
        public PhieuKhamGayMeTruocMo: number = 12,
        public GiayTuNguyenTrietSan: number = 13,
        public GiayCamKetKyThuatMoi: number = 14,
        public GiayKhamChuaBenhTheoYc: number = 15,
        public BangTheoDoiHoiTinh: number = 16,
        public BienBanCamKetGayTeGiamDauTrongDeSauMo: number = 17,
        public BangKiemAnToanNguoiBenhTuPhongMoVePhongDieuTri: number = 18,
        public BangTheoDoiGayMeHoiSuc: number = 19,
        public PhieuCongKhaiThuoc: number = 20,
        public PhieuCongKhaiVatTu: number = 21,
        public PhieuDeNghiTestTruocKhiDungThuoc: number = 22,
        public PhieuTheoDoiTruyenDich: number = 23,
        public GiayChuyenTuyen: number = 24,
        public BanKiemTruocTiemChungTreEm: number = 25,
        public PhieuChamSoc: number = 26,
        public PhieuTheoDoiTruyenMau: number = 27,
        public GiayRaVien: number = 28,
        // public BienBanHoiChanGayMe: number = 29,
        public TomTatHoSoBenhAn: number = 30,
        public GiayChungSinh: number = 31,
        public GiayCamKetTuNguyenSuDungThuoc: number = 32,
        public GiayChungNhanNghiViecHuongBHXH: number = 33,
        public GiayChungSinhMangThaiHo: number = 34,
        public BieuDoChuyenDa: number = 35,
        public PhieuCongKhaiDichVuKyThuat: number = 36,
        public PhieuCongKhaiThuocVatTu: number = 37,
        public HoSoChamSocDieuDuongHoSinh: number = 39,
        public BienBanHoiChanPhauThuatSuDungThuocCoDau: number = 40,
        public GiayNghiDuongThai: number = 41,
        public GiayChungNhanPhauThuat: number = 42,
        public GiayCamKetKyThuatMoiHS = 44,
        public GiayThoaThuanLuaChonDichVuKhamChuabenhTheoYeuCau: number = 43,
        ){}
}
