export class HoSoChamSocDieuDuongHoSinh {
    public constructor(
        public Id: number = null,
        public HoVaTen: string = null,
        public Tuoi: number = null,
        public GioiTinh: boolean = true,
        public DiaChi: string = null,
        public NgheNghiep: string = null,
        public DienThoai: string = null,
        public HoTenNguoiNha: string = null,
        public DienThoaiLienLacNguoiNha: string = null,
        public NgayVaoVien: string = null,
        public ChanDoankhiVaoVien: string = null,
        public LyDoVaoVien: string = null,
        public KhaiThacBenhSu: string = null,
        public TienSu: string = null,
        public TienSuDiUngCo: boolean = null,
        public TienSuDiUngKhong: boolean = null,
        public TienSuDiUngneuCo: string = null,
        public CoHutThuoc: boolean = null,
        public CoNghienRuouBia: boolean = null,
        public NguoiBenhCoKhuyetTat: string = null,
        public TinhTrangHienTaiCuaNB: string = null,
        public TinhTrangTinhTao :boolean = null,
        public TinhTrangMe :boolean = null,
        public TinhTrangLoMo :boolean = null,
        public KeHoachChamSocVaTheoDoi: string = null,
        public NBKhoi :boolean = null,
        public BSChoVe :boolean = null,
        public ChuyenVien :boolean = null,
        public NangXinVe :boolean = null,
        public DanhGiaTinhTrangNBKhiRaVien: string = null,
        public HuongDanNBNhungDieuCanThiet: string = null,
        public GiayRaVien :boolean = null,
        public DonThuoc :boolean = null,
        public BienLaiThanhToanVienPhi :boolean = null,
        public GiayChungNhanPhauThuat :boolean = null,
        public GiayChungSinh :boolean = null,
        public HenDenKham :string = null,
        public HoSinhTruong :string = null,
        public HoSinhChamSocNguoiBenh :string = null,
        ){}
}
export class NoiTruHoSoKhacHoSoChamSocDieuDuongHoSinh {
    constructor(
        public Id: number = 0,
        public YeuCauTiepNhanId: number = null,
        public LoaiHoSoDieuTriNoiTru: number = null,
        public ThongTinHoSo: string = null,
    ) { }
}