name: Run Angular App with Public URL

on:
  push:
    branches:
      - main

jobs:
  build-and-serve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10

      - name: Install dependencies
        run: npm install

      - name: Add Ngrok Authtoken
        run: npx ngrok authtoken 2r13IymzhSkH29ThtKzB4R9xMrU_4GV336h3Zr83LhDzBmgvT

      - name: Start Angular App and Ngrok
        run: |
          nohup npm start -- --disable-host-check --host 0.0.0.0 & 
          sleep 10  # Wait for the Angular app to start
          nohup npx ngrok http 4202 &  # Run ngrok in the background
