name: Run Angular App with Public URL

on:
  push:
    branches:
      - main

jobs:
  build-and-serve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10

      - name: Install dependencies
        run: npm install

      - name: Start Angular App
        run: |
          npm start &
          npx ngrok http 4200
